version: 0.0
os: windows
files:
  - source: \build_output\CoreApplicationForAWS
    destination: C:\Websites\CoreApplication
    file_exists_behavior: OVERWRITE
  #- #source: scripts/virtualhost.conf
    #destination: /home/ec2-user/aspnetcoreapp
    #destination: /inetpub/wwwroot
#hooks:
 # ApplicationStop:
    #- location: scripts/stop_service
     # timeout: 300
     # runas: root

 # BeforeInstall:
    #- location: scripts/remove_application
     # timeout: 300
     # runas: root

 # AfterInstall:
    #- location: scripts/install_dotnetcore
     # timeout: 500
     # runas: root

    #- location: scripts/install_httpd
     # timeout: 300
     # runas: root

 # ApplicationStart:
    #- location: scripts/start_service
      #timeout: 300
      #runas: root
#version: 0.0
#os: windows
#files:
 # - source: \
  #  destination: C:\inetpub\wwwroot
   # file_exists_behavior: OVERWRITE
#hooks:
 # BeforeInstall:
   # - location: scripts/install_dependencies.sh
  #    timeout: 300
   #   runas: root
  #AfterInstall:
   # - location: scripts/change_permissions.sh
   #   timeout: 300
    #  runas: root
  #ApplicationStart:
   # - location: scripts/start_server.sh
   # - location: scripts/create_test_db.sh
   #   timeout: 300
    #  runas: root
  #ApplicationStop:
  #  - location: scripts/stop_server.sh
   #   timeout: 300
    #  runas: root
