version: 0.2
env:
  variables:
    changed_folders=$(git diff --dirstat=files,0 HEAD~1 | awk '{print $2}' | xargs -I {} dirname {} | awk -F '/' '{print $1}' | sort | uniq)
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore CoreApplicationForAWS/CoreApplicationForAWS.csproj
  build:
    commands:
      - dotnet build CoreApplicationForAWS/CoreApplicationForAWS.csproj
      - changed_folders=$(git diff --dirstat=files0 HEAD~1 | awk 'print $2' | xargs -I  dirname  | awk -F '/' 'print $1' | sort | uniq)
      - echo $changed_folders
  post_build:
    commands:
      #- dotnet publish -c Release -o ./app/ CoreApplicationForAWS/CoreApplicationForAWS.csproj
       - dotnet publish -c release -o ./build_output/CoreApplicationForAWS
artifacts:
  files:
     
     - scripts/**/*
     - AppSpec.yml