version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore CoreApplicationForAWS/CoreApplicationForAWS.csproj
  build:
    commands:
      - dotnet build CoreApplicationForAWS/CoreApplicationForAWS.csproj
     
  post_build:
    commands:
      #- dotnet publish -c Release -o ./app/ CoreApplicationForAWS/CoreApplicationForAWS.csproj
       - dotnet publish -c release -o ./build_output/CoreApplicationForAWS
    #ignore:
     #  - CoreApplicationForAWS/web.config
    rules:
      - changes:
        - "*.config"
        when: never
artifacts:
  files:
     - build_output/**/*
     #- folders="/"
     #- for dir in build_output/CoreApplicationForAWS/*; do echo "$dir"; if [ -f "$dir"/web.config ]; then "$dir"; fi; done
     #- for value in $(folders);do echo $value;if [$value !="/build_output/CoreApplicationForAWS/web.config"]; then $value; fi;done
     # test comment
     - scripts/**/*
     - AppSpec.yml
   #  - !*.config
  name: Sougat-$(date +%Y-%m-%d) 
 # path: |
  #  build_output/**/*
   # scripts/**/*
    
  #  !build_output/*/*.config
